# Generated by scripts/generate_filter_vocabulary.py; DO NOT EDIT.
# Source: https://api.gitguardian.com/docs
# OpenAPI info.version: 1.1.0

from enum import StrEnum
from typing import Literal, TypeAlias

__all__ = [
    "IncidentSeverity",
    "IncidentSeverityFilter",
    "IncidentSourceType",
    "IncidentSourceTypeFilter",
    "IncidentStatus",
    "IncidentStatusFilter",
    "IncidentValidity",
    "IncidentValidityFilter",
]


class IncidentSeverity(StrEnum):
    """Values generated from the public API IncidentSeverity filter."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"
    UNKNOWN = "unknown"


IncidentSeverityFilter: TypeAlias = Literal[
    "critical",
    "high",
    "medium",
    "low",
    "info",
    "unknown",
]


class IncidentSourceType(StrEnum):
    """Values generated from the public API IncidentSourceType filter."""

    BITBUCKET = "bitbucket"
    BITBUCKET_CLOUD = "bitbucket_cloud"
    GITHUB = "github"
    GITLAB = "gitlab"
    AZURE_DEVOPS = "azure_devops"
    SLACK = "slack"
    JIRA_CLOUD = "jira_cloud"
    CONFLUENCE_CLOUD = "confluence_cloud"
    MICROSOFT_TEAMS = "microsoft_teams"
    CONFLUENCE_DATA_CENTER = "confluence_data_center"
    JIRA_DATA_CENTER = "jira_data_center"
    AWS_ECR = "aws_ecr"
    AZURE_CR = "azure_cr"
    GOOGLE_ARTIFACT = "google_artifact"
    JFROG_ARTIFACT = "jfrog_artifact"
    DOCKER_HUB = "docker_hub"
    SERVICENOW = "servicenow"
    SHAREPOINT_ONLINE = "sharepoint_online"
    SHAREPOINT_ONLINE_DRIVE = "sharepoint_online_drive"
    SHAREPOINT_ONLINE_PAGES = "sharepoint_online_pages"
    MICROSOFT_ONEDRIVE = "microsoft_onedrive"
    CUSTOM_SOURCE = "custom_source"


IncidentSourceTypeFilter: TypeAlias = Literal[
    "bitbucket",
    "bitbucket_cloud",
    "github",
    "gitlab",
    "azure_devops",
    "slack",
    "jira_cloud",
    "confluence_cloud",
    "microsoft_teams",
    "confluence_data_center",
    "jira_data_center",
    "aws_ecr",
    "azure_cr",
    "google_artifact",
    "jfrog_artifact",
    "docker_hub",
    "servicenow",
    "sharepoint_online",
    "sharepoint_online_drive",
    "sharepoint_online_pages",
    "microsoft_onedrive",
    "custom_source",
]


class IncidentStatus(StrEnum):
    """Values generated from the public API IncidentStatus filter."""

    IGNORED = "IGNORED"
    TRIGGERED = "TRIGGERED"
    ASSIGNED = "ASSIGNED"
    RESOLVED = "RESOLVED"


IncidentStatusFilter: TypeAlias = Literal[
    "IGNORED",
    "TRIGGERED",
    "ASSIGNED",
    "RESOLVED",
]


class IncidentValidity(StrEnum):
    """Values generated from the public API IncidentValidity filter."""

    VALID = "valid"
    INVALID = "invalid"
    FAILED_TO_CHECK = "failed_to_check"
    NO_CHECKER = "no_checker"
    UNKNOWN = "unknown"


IncidentValidityFilter: TypeAlias = Literal[
    "valid",
    "invalid",
    "failed_to_check",
    "no_checker",
    "unknown",
]
